repos:
  # ESLint and Prettier for JavaScript/TypeScript
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npx eslint
        language: node
        files: \.(js|jsx|ts|tsx)$
        require_serial: false
        additional_dependencies:
          - eslint
        args: [--fix, --max-warnings=0]

      - id: prettier
        name: Prettier
        entry: npx prettier
        language: node
        files: \.(js|jsx|ts|tsx|json|css|md)$
        args: [--write]
        additional_dependencies:
          - prettier

      - id: typescript-check
        name: TypeScript Type Check
        entry: npx tsc
        language: node
        files: \.(ts|tsx)$
        args: [--noEmit]
        additional_dependencies:
          - typescript

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Security checks
  - repo: local
    hooks:
      - id: npm-audit
        name: NPM Security Audit
        entry: npm audit
        language: system
        pass_filenames: false
        always_run: true