repos:
  # ESLint and Prettier for JavaScript
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bun run lint
        language: system
        files: \.(js|ts)$
        require_serial: false

      - id: prettier
        name: Prettier
        entry: bun run format
        language: system
        files: \.(js|ts|json|md)$

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Security checks
  - repo: local
    hooks:
      - id: bun-audit
        name: Bun Security Audit
        entry: bun audit
        language: system
        pass_filenames: false
        always_run: true